version: "2"
services:
  suctre:
    image: tutum/apache-php
    ports:
      - 9000:80
    volumes:
      - .:/var/www/html/suctre.vn
    environment:
      - ALLOW_OVERRIDE=true
    links:
      - mysql

  mysql:
    image: mysql:5.6
    ports:
      - 3307:3306
    volumes:
      - ./mysql-data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=suctre
    cpu_shares: 512
    mem_limit: 536870912