version: "2"
services:
  suctre:
    image: suctre:latest
    working_dir: /app/suctre.vn
    ports:
      - 9000:80
    volumes:
      - .:/var/www/html/suctre.vn
    entrypoint: ./docker-entrypoint.sh
    environment:
      - ALLOW_OVERRIDE=true
    links:
      - mysql

  mysql:
    image: mysql:5.6
    ports:
      - 3307:3306
    volumes:
      - ./mysql-data:/var/lib/mysql/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=JST
    cpu_shares: 512
    mem_limit: 536870912